name: Main

on:
  push:
    tags:
      - "v*.*.*"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      # We use the `arduino/setup-arduino-cli` action to install and
      # configure the Arduino CLI on the system.
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      # We then install the platform, which one will be determined
      # dynamically by the build matrix.
      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      # Finally, we compile the sketch, using the FQBN that was set
      # in the build matrix.
      - name: Compile Sketch
        run: |
          echo pwd
          cd blink
          arduino-cli compile --fqbn arduino:avr:uno -v --build-path  ../blinked
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Release.txt
            blinked/blink.bin
